# Dataset configuration
dataset_path: jonluj/pir_full

# Model configuration
model_name_or_path: jonluj/r1_qwen7b_secreason
torch_dtype: bfloat16
tokenizer_name_or_path: jonluj/r1_qwen7b_secreason
trust_remote_code: false
attn_implementation: flash_attention_2
device_map:

# LoRA configuration
peft_enabled: false
lora_r:
lora_alpha:
lora_dropout:
bias:
target_modules:

# Training configuration
optim: adamw_torch
learning_rate: 1.0e-6
adam_beta1: 0.9
adam_beta2: 0.99
weight_decay: 0.1
warmup_ratio: 0.1
lr_scheduler_type: cosine
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
num_generations: 24
num_train_epochs: 1
max_grad_norm: 1.0
max_prompt_length: 1024
max_completion_length: 1024
run_prefix: r1_qwen7b_grpo_pir
output_dir: ./outputs
logging_steps: 5
logging_strategy: steps
bf16: true
fp16: false
save_steps: 100
save_total_limit: 2
use_vllm: true
# eval_strategy: steps
# eval_steps: 100
# load_best_model_at_end: true
# metric_for_best_model: eval_loss
# gradient_checkpointing: true
# gradient_checkpointing_kwargs:
#   use_reentrant: False
report_to: wandb
wandb_project: qwen_reasoning
log_on_each_node: false
seed: 42
log_level: info
