# Dataset configuration
dataset_path: jonluj/secalign_claude_preference_dpo_NaiveCompletion
split: train
test_size: 0.05
pad_free: false # need to specify here because it goes to the collator

# Model configuration
model_name_or_path: /scratch/public_models/huggingface/Qwen/Qwen3-8B
torch_dtype: bfloat16
tokenizer_name_or_path: /scratch/public_models/huggingface/Qwen/Qwen3-8B
trust_remote_code: false
attn_implementation: flash_attention_2
device_map:

# LoRA configuration
peft_enabled: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
bias: none
target_modules: all-linear

# Training configuration
optim: adamw_torch
learning_rate: 5.0e-6
beta: 0.01
weight_decay: 0.1
warmup_ratio: 0.1
lr_scheduler_type: cosine
per_device_train_batch_size: 1
num_train_epochs: 3
max_grad_norm: 1.0
run_prefix: dpo_secalign_lora
output_dir: ./outputs
logging_steps: 5
logging_strategy: steps
bf16: true
fp16: false
tf32: true
save_steps: 100
save_total_limit: 2
eval_strategy: steps
eval_steps: 100
load_best_model_at_end: true
metric_for_best_model: eval_loss
# gradient_checkpointing: true
# gradient_checkpointing_kwargs:
#   use_reentrant: False
report_to: wandb
wandb_project: qwen_reasoning
log_on_each_node: false
max_length: 4096
seed: 42
log_level: info
